### ISSUE TITLE
clipCopy在safari 10 下没能复制成功

### ISSUE THREAD

**Issue by taokd** [JimmyVV/react-copybtn#1]
直接调用`clipCopy(data)`方法，发现剪贴板里面没有要复制的内容；
调试发现，此时 document.execCommand('copy') 执行结果为false，没能触发copy事件;

切换为`inputCopy(data)`， 复制内容成功；
结合[execCommand MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand), Copies the current selection to the clipboard；  似乎需要选中一些内容，才能成功触发copy。

**Comment by JimmyVV** [comment]
恩，是这样的。inputCopy 之所以能成功是因为，它并不是让你来选中，而是手动让你固定需要复制的信息。

> 不过，在手机端中，规矩是，你可以在可编辑的元素中触发 cut 和 paste , 只能在有效的 选中 元素中，触发 copy。

详细的你可以参考一下 [H5 复制](https://www.villainhr.com/page/2016/11/27/H5%20%E7%9A%84%E5%A4%8D%E5%88%B6%E6%93%8D%E4%BD%9C)。

**Comment by taokd** [comment]
:blush: thanks.
